services:
  document-storage:
    image: vasilegov/document-storage:${ENVIRONMENT}
    container_name: document-storage-${ENVIRONMENT}
    environment:
      - DB_PORT=${DB_PORT}
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - document-storage-files:/app/files
    ports:
      - ${DOCUMENT_STORAGE_PORT}:8080
    depends_on:
      - database

  database:
    image: mysql:8.0.43
    container_name: mysql-database-${ENVIRONMENT}
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  document-storage-files:
    name: document-storage-files-${ENVIRONMENT}
  mysql-data:
    name: mysql-data-${ENVIRONMENT}
